server:
  port: 8080

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/shiro1?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true&useSSL=false&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

mybatis-plus:
  type-aliases-package: com.example.shiro1.entity
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      table-underline: true
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      call-setters-on-nulls: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
